name: build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: build
      run: nix build .